language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1

cache:
  - bundler

before_install:
  - gem install bundler # To use 1.8.x or later

before_script:
  - bundle exec rake update_assets
