language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3

cache:
  - bundler

before_install:
  - gem update --system # Need for Ruby 2.5.0. https://github.com/travis-ci/travis-ci/issues/8978
  - gem install bundler # To use 1.8.x or later

before_script:
  - bundle exec rake update_assets
